Check the length of array instead bool rep
opendatahub-io/jupyterhub-singleuser-profiles pull request #211
Opened 2022-01-17 19:51 UTC by vpavlin

2022-01-17 20:07 UTC, DaoDaoNoCode approved these changes
LGTM, thanks!

2022-01-18 11:36 UTC, jeff-phillips-18 commented on jupyterhub_singleuser_profiles/ui/src/SizesForm/SizesForm.tsx
> +    if (userConfig && sizeDescriptions.length > 0) {
I think we should ensure `sizeDescriptions` is set before checking length as well.
```suggestion
    if (userConfig && sizeDescriptions?.length) {
```

2022-01-18 11:38 UTC, jeff-phillips-18 requested changes
One request

2022-01-18 11:48 UTC, jeff-phillips-18 approved these changes

2022-01-18 13:17 UTC, merged